### ISSUE TITLE
Configuration messed up with nigiri and database

### ISSUE THREAD

**Issue by sjwhitak** [motis-project/motis#501]
Hello, thank you for making this project!

I'm currently trying to set up a live bus position for Rhode Island and nothing else. I followed the [installation](https://github.com/motis-project/motis/wiki/Installation-and-Setup) and [configuration](https://github.com/motis-project/motis/wiki/Configuration) setup you set up which is very nice. My configuration, `config.ini` is minimal:

```ini
modules=tiles
modules=nigiri

server.static_path=motis/web
#dataset.no_schedule=true

[import]
paths=schedule-us-ri-RIPTA:us-ri_RIPTA.gtfs.zip
paths=osm:rhode-island-latest.osm.pbf
paths=coastline:rhode-island-latest-free.shp.zip

[tiles]
profile=motis/tiles-profiles/background.lua

[nigiri]
gtfsrt=us-ri-RIPTA|http://realtime.ripta.com:81/api/tripupdates?format=gtfs.proto
```

The `osm` and `coastline` data is from: http://download.geofabrik.de/north-america/us/rhode-island.html

I commented out `dataset.no_schedule=true` because no matter what, I get:
```
options error: unrecognised option 'dataset.no_schedule'
```
But if I comment it out, motis runs just fine. I don't know what's going on there but if it works, it works.

When I run motis, I get the map displaying and the buses work just fine! But I currently only have display for only 4-5 buses using the [RIPTA GTFS feed](https://www.transit.land/operators/o-drm-rhodeislandpublictransitauthority). When I directly pull from the real-time feed, I see a few more buses. I believe this is an issue with RIPTA's possibly poor following with their GTFS data and maybe motis is expecting a different format (some of their GTFS bus stop positions are 15+ meters off or completely missing! I need to talk to RIDOT again). I get the following errors:

```
(base) steven@debian:~/code/motis$ ./motis/motis 
Used Options:

  server.host: 0.0.0.0
  server.port: 8080
  server.cert_path: ::dev::
  server.priv_key_path: ::dev::
  server.dh_path: ::dev::
  server.api_key: 
  server.log_path: 
  server.static_path: motis/web


  import.paths: schedule-us-ri-RIPTA:us-ri_RIPTA.gtfs.zip, osm:rhode-island-latest.osm.pbf, coastline:rhode-island-latest-free.shp.zip
  import.data_dir: data
  import.require_successful: 1


  modules: tiles, nigiri
  exclude_modules: 


  remotes: 


  mode: server
  batch_input_file: queries.txt
  batch_output_file: responses.txt
  init: 
  num_threads: 12
  direct: 0


  gbfs.update_interval: 5
  gbfs.urls: 
  gbfs.db_size: 1099511627776


  intermodal.router: routing
  intermodal.revise: 0
  intermodal.timeout: 0


  nigiri.no_cache: 0
  nigiri.adjust_footpaths: 1
  nigiri.match_duplicates: 0
  nigiri.max_footpath_length: 65535
  nigiri.first_day: TODAY
  nigiri.num_days: 2
  nigiri.lookup: 1
  nigiri.guesser: 1
  nigiri.railviz: 1
  nigiri.routing: 1
  nigiri.link_stop_distance: 100
  nigiri.default_timezone: 
  nigiri.gtfsrt: us-ri-RIPTA|http://realtime.ripta.com:81/api/tripupdates?format=gtfs.proto
  nigiri.gtfsrt_paths: 
  nigiri.gtfsrt_incremental: 0
  nigiri.debug: 0


  osr.lock: 1


  osrm.profiles: 


  parking.db_max_size: 549755813888
  parking.max_walk_duration: 10
  parking.import.edge_rtree_max_size: 3221225472
  parking.import.area_rtree_max_size: 1073741824
  parking.import.lock_rtrees: 0
  parking.import_osm: 1
  parking.ppr_exact: 1
  parking.parkendd_endpoints: 
  parking.parkendd_update_interval: 300


  ppr.import.use_dem: 0
  ppr.profile: 
  ppr.edge_rtree_max_size: 3221225472
  ppr.area_rtree_max_size: 1073741824
  ppr.lock_rtrees: 0
  ppr.prefetch_rtrees: 1
  ppr.verify_graph: 0
  ppr.check_integrity: 1


  tiles.profile: motis/tiles-profiles/background.lua
  tiles.import.use_coastline: 0
  tiles.import.flush_threshold: 10000000
  tiles.db_size: 1099511627776


      nigiri: FINISHED
       tiles: FINISHED
[info][2024-05-12T04:09:03Z+0000][nigiri.cc:310] Starting GTFS-RT update: fetch URLs
[debg][2024-05-12T04:09:03Z+0000][logging.h:68] http request GET http://realtime.ripta.com:81/api/tripupdates?format=gtfs.proto
2024-05-12T04:09:03Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3776558" start_time: "00:17:00" start_date: "20240512" route_id: "11" 
2024-05-12T04:09:03Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3776657" start_time: "23:17:00" start_date: "20240511" route_id: "11" 
[info][2024-05-12T04:09:03Z+0000][nigiri.cc:348] us-ri-RIPTA: total_entities=8, total_entities_success=6 (75%), trip_resolve_error=2 (25%)
Serving static files from /home/steven/code/motis/motis/web
[info][2024-05-12T04:09:03Z+0000][main.cc:179] system boot finished
[info][2024-05-12T04:09:03Z+0000][nigiri.cc:310] Starting GTFS-RT update: fetch URLs
[debg][2024-05-12T04:09:03Z+0000][logging.h:68] http request GET http://realtime.ripta.com:81/api/tripupdates?format=gtfs.proto
2024-05-12T04:09:03Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3776558" start_time: "00:17:00" start_date: "20240512" route_id: "11" 
2024-05-12T04:09:03Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3776657" start_time: "23:17:00" start_date: "20240511" route_id: "11" 
[info][2024-05-12T04:09:03Z+0000][nigiri.cc:348] us-ri-RIPTA: total_entities=8, total_entities_success=6 (75%), trip_resolve_error=2 (25%)
```

Now, this issue is being posted way past midnight now, but during the day I was getting 40% or 20% success rate with much more buses failing to resolve. 

I guess it's not the end of the world if this can't be fixed, and if it won't, I'd like to be able to figure out the root cause of this so I can intercept the GTFS-RT data and modify it to format properly for motis for these broken buses. Thanks!

**Comment by felixguendling** [comment]
Release v0.12.1 should fix the problems.

Problems were:

- The `routes.txt` does not refer to any `agency_id` which seems to be valid in the special case that the `agency.txt` contains exactly one agency. This special case is not handled accordingly. Before, the agency was missing which lead to problems resolving the timezone.
- The issue mentioned above that MOTIS handled `start_time` + `start_date` like a database key. With the new version, it can match `00:17:00` on the next day to `24:17:00` on the previous day.

Since this changes the matching logic, it makes sense to also check matching statistics on other feeds. We have a test suite with all kinds of special cases and it's working for all of them. But still @everybody: please check with your feeds and report bugs if this introduced any.

**Comment by sjwhitak** [comment]
I'm test running a server for a day and I'll let you know if that fixes it. Currently it's been two hours with 100% entity success, but I'll let you know if there's an issue with the 00 vs 24 boundary, thanks for this.

**Comment by felixguendling** [comment]
Sounds good. Thanks for testing! 100% looks like the issue is solved now :)

**Comment by sjwhitak** [comment]
Sorry to reopen the ticket, but I am receiving failed responses still only during the end of the night. Here is my configuration (might be a bit different possibly but still the same).

The motis response:
```
(base) steven@debian:~/code/motis$ ./motis/motis 
Used Options:

  server.host: 0.0.0.0
  server.port: 8080
  server.cert_path: ::dev::
  server.priv_key_path: ::dev::
  server.dh_path: ::dev::
  server.api_key: 
  server.log_path: 
  server.static_path: motis/web


  import.paths: schedule-us-ri-RIPTA:us-ri_RIPTA.gtfs.zip, osm:rhode-island-latest.osm.pbf, coastline:rhode-island-latest-free.shp.zip
  import.data_dir: data
  import.require_successful: 1


  modules: tiles, nigiri
  exclude_modules: 


  remotes: 


  mode: server
  batch_input_file: queries.txt
  batch_output_file: responses.txt
  init: 
  num_threads: 12
  direct: 0


  gbfs.update_interval: 5
  gbfs.urls: 
  gbfs.db_size: 1099511627776


  intermodal.router: nigiri
  intermodal.revise: 0
  intermodal.timeout: 0


  nigiri.no_cache: 0
  nigiri.adjust_footpaths: 1
  nigiri.match_duplicates: 0
  nigiri.max_footpath_length: 65535
  nigiri.first_day: TODAY
  nigiri.num_days: 2
  nigiri.lookup: 1
  nigiri.guesser: 1
  nigiri.railviz: 1
  nigiri.routing: 1
  nigiri.link_stop_distance: 100
  nigiri.default_timezone: 
  nigiri.gtfsrt: us-ri-RIPTA|http://realtime.ripta.com:81/api/tripupdates?format=gtfs.proto
  nigiri.gtfsrt_paths: 
  nigiri.gtfsrt_incremental: 0
  nigiri.debug: 0


  osr.lock: 1


  osrm.profiles: 


  parking.db_max_size: 549755813888
  parking.max_walk_duration: 10
  parking.import.edge_rtree_max_size: 3221225472
  parking.import.area_rtree_max_size: 1073741824
  parking.import.lock_rtrees: 0
  parking.import_osm: 1
  parking.ppr_exact: 1
  parking.parkendd_endpoints: 
  parking.parkendd_update_interval: 300


  ppr.import.use_dem: 0
  ppr.profile: 
  ppr.edge_rtree_max_size: 3221225472
  ppr.area_rtree_max_size: 1073741824
  ppr.lock_rtrees: 0
  ppr.prefetch_rtrees: 1
  ppr.verify_graph: 0
  ppr.check_integrity: 1


  tiles.profile: motis/tiles-profiles/background.lua
  tiles.import.use_coastline: 0
  tiles.import.flush_threshold: 10000000
  tiles.db_size: 1099511627776


      nigiri: FINISHED
       tiles: FINISHED
[info][2024-05-16T03:12:19Z+0000][nigiri.cc:310] Starting GTFS-RT update: fetch URLs
[debg][2024-05-16T03:12:19Z+0000][logging.h:68] http request GET http://realtime.ripta.com:81/api/tripupdates?format=gtfs.proto
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795513" start_time: "22:52:00" start_date: "20240515" route_id: "20" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795512" start_time: "23:15:00" start_date: "20240515" route_id: "20" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3797547" start_time: "22:41:00" start_date: "20240515" route_id: "54" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3797520" start_time: "23:12:00" start_date: "20240515" route_id: "51" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3797550" start_time: "23:02:00" start_date: "20240515" route_id: "51" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795703" start_time: "22:00:00" start_date: "20240515" route_id: "66" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796152" start_time: "22:52:00" start_date: "20240515" route_id: "21" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796645" start_time: "23:01:00" start_date: "20240515" route_id: "55" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796504" start_time: "23:06:00" start_date: "20240515" route_id: "56" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796395" start_time: "23:18:00" start_date: "20240515" route_id: "31" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796506" start_time: "23:31:00" start_date: "20240515" route_id: "31" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796938" start_time: "22:47:00" start_date: "20240515" route_id: "50" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796050" start_time: "23:17:00" start_date: "20240515" route_id: "19" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795321" start_time: "22:35:00" start_date: "20240515" route_id: "1" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795348" start_time: "22:28:00" start_date: "20240515" route_id: "1" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3798040" start_time: "22:38:00" start_date: "20240515" route_id: "11" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3797884" start_time: "22:47:00" start_date: "20240515" route_id: "33" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3798022" start_time: "23:18:00" start_date: "20240515" route_id: "11" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3798026" start_time: "22:58:00" start_date: "20240515" route_id: "11" 
2024-05-16T03:12:19Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3798021" start_time: "23:10:00" start_date: "20240515" route_id: "11" 
[info][2024-05-16T03:12:19Z+0000][nigiri.cc:348] us-ri-RIPTA: total_entities=30, total_entities_success=10 (33.3333%), trip_resolve_error=20 (66.6667%)
Serving static files from /home/steven/code/motis/motis/web
[info][2024-05-16T03:12:19Z+0000][main.cc:179] system boot finished
[info][2024-05-16T03:12:19Z+0000][nigiri.cc:310] Starting GTFS-RT update: fetch URLs
[debg][2024-05-16T03:12:19Z+0000][logging.h:68] http request GET http://realtime.ripta.com:81/api/tripupdates?format=gtfs.proto
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795513" start_time: "22:52:00" start_date: "20240515" route_id: "20" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795512" start_time: "23:15:00" start_date: "20240515" route_id: "20" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3797547" start_time: "22:41:00" start_date: "20240515" route_id: "54" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3797520" start_time: "23:12:00" start_date: "20240515" route_id: "51" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3797550" start_time: "23:02:00" start_date: "20240515" route_id: "51" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795703" start_time: "22:00:00" start_date: "20240515" route_id: "66" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796152" start_time: "22:52:00" start_date: "20240515" route_id: "21" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796645" start_time: "23:01:00" start_date: "20240515" route_id: "55" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796504" start_time: "23:06:00" start_date: "20240515" route_id: "56" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796395" start_time: "23:18:00" start_date: "20240515" route_id: "31" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796506" start_time: "23:31:00" start_date: "20240515" route_id: "31" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796938" start_time: "22:47:00" start_date: "20240515" route_id: "50" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3796050" start_time: "23:17:00" start_date: "20240515" route_id: "19" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795321" start_time: "22:35:00" start_date: "20240515" route_id: "1" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3795348" start_time: "22:28:00" start_date: "20240515" route_id: "1" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3798040" start_time: "22:38:00" start_date: "20240515" route_id: "11" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3797884" start_time: "22:47:00" start_date: "20240515" route_id: "33" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3798022" start_time: "23:18:00" start_date: "20240515" route_id: "11" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3798026" start_time: "22:58:00" start_date: "20240515" route_id: "11" 
2024-05-16T03:12:20Z | [error][rt.gtfs.resolve               ] could not resolve (tag=us-ri-RIPTA) trip_id: "3798021" start_time: "23:10:00" start_date: "20240515" route_id: "11" 
[info][2024-05-16T03:12:20Z+0000][nigiri.cc:348] us-ri-RIPTA: total_entities=30, total_entities_success=10 (33.3333%), trip_resolve_error=20 (66.6667%)
```

When using the following script:
```python
url = 'http://realtime.ripta.com:81/api/vehiclepositions?format=gtfs.proto'

from google.transit import gtfs_realtime_pb2
import requests

feed = gtfs_realtime_pb2.FeedMessage()
response = requests.get(url)
feed.ParseFromString(response.content)
open('dump.json','w').write(str(feed.entity))
```

I receive the following GTFS data: [test.log](https://github.com/motis-project/motis/files/15329289/test.log) at around the same time. When mapping them, the following trips seem to fail:

```
vehicle {
  trip {
    trip_id: "3795513"
    route_id: "20"
    start_time: "22:52:00"
    start_date: "20240515"
  }
  vehicle {
    id: "1317"
    label: "1317"
    license_plate: " "
  }
  position {
    latitude: 41.8248978
    longitude: -71.4114
    bearing: 210
  }
  stop_id: "10030"
  current_status: STOPPED_AT
  timestamp: 1715829109
}
...
vehicle {
  trip {
    trip_id: "3798040"
    route_id: "11"
    start_time: "22:38:00"
    start_date: "20240515"
  }
  vehicle {
    id: "2201"
    label: "2201"
    license_plate: " "
  }
  position {
    latitude: 41.8633614
    longitude: -71.399292
    bearing: 345
    speed: 10.72896
  }
  stop_id: "21450"
  timestamp: 1715829135
}
...
```

For trip id 3795513, the bus is done for the night ([route 20](https://www.ripta.com/routes/20/)) and the current_status is STOPPED, (at the Kennedy Plaza in Rhode Island), but the route 11 (actually the [R-line](https://www.ripta.com/routes/11-1/)) seems to keep on going for another hour and is currently moving, though motis is failing to align it. The bus starts at 22:38 and ends at 23:17, so I'm unsure what's happening here. 

It's really not a worry and you can push this back if you need be. I only use this for commuting to/from work since motis is better than google maps for my specific need. So motis having resolving issues near the midnight boundary doesn't affect me, but hopefully I can help give more test data. Thanks!

**Comment by felixguendling** [comment]
I added your first trip to the test suite in [this commit](https://github.com/motis-project/nigiri/commit/82b8484f65f3964bd95cbeca4729d277d40f9bfd) and the problem cannot be reproduced. The previous ones were reproducible with test cases.

So my guess is that your GTFS-static and GTFS-RT might not be in-sync? What's the update cycle of the GTFS-static data? If a new GTFS-static dataset is released during the night but MOTIS uses still the old one, it's to be expected that some trips can't be matched.

Regarding vehicle positions: MOTIS currently does not parse them. What you see on the map is a linear interpolation between stop positions.

**Comment by sjwhitak** [comment]
GTFS-static gets updated once every few months, so I don't believe that's an issue there. Here's an email I sent RIPTA when I was importing the data into OpenStreetMaps:

>In case you’re not aware, RIPTA makes planned service changes generally three times a year (January, June, and August/September) and when we make those changes we also update the GTFS data on our website. Most of these changes are not drastic – adding or removing a bus stop, small route deviations, retiming of schedules, etc. – but to be most accurate you may need to occasionally update the data or at least note the publish date.

In case this is helpful, I set up an instance of motis on https://sjwhitak.net and I am dumping the logs into https://sjwhitak.net/log.txt . Just please don't pan around too much in this instance since it will dirty the logs with a bunch of "tile not found" errors. I only have the Rhode Island map downloaded and I'm saving the logs to a file.

I should receive ~100% accuracy throughout the day and then once it gets around 10-11pm EST, it starts to falter.
