### ISSUE TITLE
OSR park&ride routing

### ISSUE THREAD

**Issue by PartTimeDataScientist** [motis-project/motis#739]
I ran a "routeability" analysis on all Park&Ride parking lots in NRW and while there are some cases that lack connection to the road network (from which I have fixed at least two already) I also found some cases that I think should be routeable with the car profile as far as I understand the allowed tags and the tagset of these cases. 

Some examples:
https://ideditor.netlify.app/#background=nrw_ortho_wms&disable_features=boundaries&map=18.00/51.84923/6.86375&id=w53843457
https://ideditor.netlify.app/#background=nrw_ortho_wms&disable_features=boundaries&map=18.00/51.53645/6.96842&id=w345627055
https://ideditor.netlify.app/#background=nrw_ortho_wms&disable_features=boundaries&map=18.00/51.48579/6.98777&id=w645053814

Is there anything I am missing? Does this require fixing on OSM-side or OSR-Side?

In general: Is it sufficient if there is a small connection to the parking area, i.e. would it be sufficient to connect the following area with a small way from the north or do I need to model all ways on the parking lot?

https://ideditor.netlify.app/#background=nrw_ortho_wms&disable_features=boundaries&map=18.82/51.22166/6.86503&id=w910991202

**Comment by felixguendling** [comment]
Looking at the node list here:
https://www.openstreetmap.org/way/53843457#map=19/51.849238/6.863792&layers=D

There are no nodes that are also part of any other way. So this is an island (not connected to the street network).

This has another way listed that are connected to nodes in the list:
https://www.openstreetmap.org/way/345627055

However, it is itself also a parking way not connected to the outside street network. So again no connection.

The last one is connected to another way that's connected to the street network. But it's marked as `access=private`:
https://www.openstreetmap.org/way/645053814
https://www.openstreetmap.org/way/645053807
https://www.openstreetmap.org/way/234306323

**Comment by felixguendling** [comment]
Since all cases seem to be either unconnected or connected but tagged with `access=private`, I would not consider them bugs in OSR since we don't have any "auto-connection" post-processing step after extraction. Please let me know if I missed something.

**Comment by PartTimeDataScientist** [comment]
> Looking at the node list here: https://www.openstreetmap.org/way/53843457
> There are no nodes that are also part of any other way. So this is an island (not connected to the street network).

But the query is starting at coordinates and not at the parking lot OSM ID. Crossing through the parking lot there is a way which (to me) seems to be connected to the street network and is well within the 25m default snapping radius (center coordinates are precisely the query starting coordinates):

https://www.openstreetmap.org/way/169334889#map=19/51.849230/6.863754

> This has another way listed that is connected to nodes in the list: https://www.openstreetmap.org/way/345627055
> However, it is itself also a parking way not connected to the outside street network. So again no connection.

But as with the first case the other way is allowed and connected and very close to the query coordinates:
https://www.openstreetmap.org/way/1340358017#map=19/51.536470/6.968470

Why is this way not selected as starting point? 

> The third example is connected to another way that's connected to the street network. But it's marked as `access=private`: https://www.openstreetmap.org/way/645053814 https://www.openstreetmap.org/way/645053807 https://www.openstreetmap.org/way/234306323
> > Is it sufficient if there is a small connection to the parking area
> 
> Yes.

This one was clear to me, that's why I was asking about making only a small connection to the `amenity=parking` area...

Anyhow: with the two obvious issues I fixed we are now at 11/970 or ~1% failure rate for NRW which is much lower than expected. For reference purposes I'll check other states as well...

**Comment by felixguendling** [comment]
If the closest node is within an island there's currently no way for osr to know this. Here's more info + a way to fix it:

https://github.com/public-transport/transitous/issues/820#issuecomment-2619572520

**Comment by PartTimeDataScientist** [comment]
> If the closest node is within an island there's currently no way for osr to know this. Here's more info + a way to fix it:
> 
> [public-transport/transitous#820 (comment)](https://github.com/public-transport/transitous/issues/820#issuecomment-2619572520)

Understood - but to my understanding that means that at least for the cases where there is a `highway=service` way through the "island" that's more of an osr "limitation" than faulty OSM mapping.

Anyway: Would it be sufficient for these cases to split the access-way at the outer border of the parking lot an connect it to the routable netowrk?

![Image](https://github.com/user-attachments/assets/bddfeec8-1221-4282-9b63-63eac1720cf8)

**Comment by felixguendling** [comment]
In general: yes, connecting the parking streets with the area at one point is sufficient.
Here: none of the routers can access this parking because someone tagged the road leading there as `access: psv` which is blacklisted (only accessible by public service vehicles such as taxis and buses).

**Comment by felixguendling** [comment]
I made a mistake that maxMatchingDistance was not used for direct connections. This should be fixed with: https://github.com/motis-project/motis/pull/743
It also introduces `config.timetable.max_matching_distance` to allow setting the maximum matching distance for footpath preprocessing.

**Comment by HendrikSmd** [comment]
@felixguendling 

> If the closest node is within an island there's currently no way for osr to know this. Here's more info + a way to fix it:

Hasn't this been fixed with https://github.com/motis-project/osr/commit/cd480ba15acaa8c67c53f6eccb60be7271fff831 ?

**Comment by felixguendling** [comment]
Yes, but in general P+R routing is still not fixed.
https://github.com/motis-project/osr/pull/112

**Comment by PartTimeDataScientist** [comment]
@MichaelKutzner is currently working on fixing unreachable "parking islands" during the OSM-import to improve the situation (currently focused on MIV and not on bike parking but the approach should be generalizeable later)!
